name: CI
on: push
jobs:
  install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/template/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install
        working-directory: ./template
  lint:
    needs: install
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/template/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm run lint
        working-directory: ./template
  type-check:
    needs: install
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/template/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm run type-check
        working-directory: ./template
  # test:
  #   needs: install
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.x

  #     - uses: actions/cache@v2
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/template/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-

  #     - run: npm run test:unit
  #       working-directory: ./template
